#ifndef _ASCII_H
#define _ASCII_H

#define X_ASCIIS( X )\
	X( NUL,       EOS,     Eos,     RET )		/* '\0' */\
	X( SOH,       NEXT,    Next,    JMP )		/* 1 */\
	X( STX,       NEXT,    Next,    JMP )		/* 2 */\
	X( ETX,       NEXT,    Next,    JMP )		/* 3 */\
	X( EOT,       NEXT,    Next,    JMP )		/* 4 */\
	X( ENQ,       NEXT,    Next,    JMP )		/* 5 */\
	X( ACK,       NEXT,    Next,    JMP )		/* 6 */\
	X( BEL,       NEXT,    Next,    JMP )		/* 7 */\
	X( BS,        NEXT,    Next,    JMP )		/* 8 */\
	X( HT,        NEXT,    Next,    JMP )		/* 9 */\
	X( LF,        LINE,    Line,    JMP )		/* '\n' */\
	X( VT,        NEXT,    Next,    JMP )		/* '\t' */\
	X( FF,        NEXT,    Next,    JMP )		/* '\f' */\
	X( CR,        NEXT,    Next,    JMP )		/* '\r' */\
	X( SO,        NEXT,    Next,    JMP )		/* 14 */\
	X( SI,        NEXT,    Next,    JMP )		/* 15 */\
	X( DLE,       NEXT,    Next,    JMP )		/* 16 */\
	X( DC1,       NEXT,    Next,    JMP )		/* 17 */\
	X( DC2,       NEXT,    Next,    JMP )		/* 18 */\
	X( DC3,       NEXT,    Next,    JMP )		/* 19 */\
	X( DC4,       NEXT,    Next,    JMP )		/* 20 */\
	X( NAK,       NEXT,    Next,    JMP )		/* 21 */\
	X( SYN,       NEXT,    Next,    JMP )		/* 22 */\
	X( ETB,       NEXT,    Next,    JMP )		/* 23 */\
	X( CAN,       NEXT,    Next,    JMP )		/* 24 */\
	X( EM,        NEXT,    Next,    JMP )		/* 25 */\
	X( SUB,       NEXT,    Next,    JMP )		/* 26 */\
	X( ESC,       NEXT,    Next,    JMP )		/* 27 */\
	X( FS,        NEXT,    Next,    JMP )		/* 28 */\
	X( GS,        NEXT,    Next,    JMP )		/* 29 */\
	X( RS,        NEXT,    Next,    JMP )		/* 30 */\
	X( US,        NEXT,    Next,    JMP )		/* 31 */\
	X( SPACE,     NEXT,    Next,    JMP )		/* ' ' */\
	X( EXCL,      NOT,     Not,     RET )		/* '!' */\
	X( DQUOTE,    NEXT,    Next,    JMP )		/* '"' */\
	X( POUND,     NEXT,    Next,    JMP )		/* '#' */\
	X( DOLLAR,    COMMENT, Comment, JMP )		/* '$' */\
	X( PERCENT,   MOD,     Mod,     RET )		/* '%' */\
	X( AMPER,     BAND,    Band,    RET )		/* '&' */\
	X( SQUOTE,    NEXT,    Next,    JMP )		/* '\'' */\
	X( LP,        LP,      Lp,      RET )		/* '(' */\
	X( RP,        RP,      Rp,      RET )		/* ')' */\
	X( ASTERISK,  MUL,     Mul,     RET )		/* '*' */\
	X( PLUS,      ADD,     Add,     RET )		/* '+' */\
	X( COMMA,     NEXT,    Next,    JMP )		/* ',' */\
	X( HYPHEN,    SUB,     Sub,     RET )		/* '-' */\
	X( PERIOD,    NEXT,    Next,    JMP )		/* '.' */\
	X( FSLASH,    DIV,     Div,     RET )		/* '/' */\
	X( ZERO,      NUM,     Num,     RET )		/* '0' */\
	X( ONE,       NUM,     Num,     RET )		/* '1' */\
	X( TWO,       NUM,     Num,     RET )		/* '2' */\
	X( THREE,     NUM,     Num,     RET )		/* '3' */\
	X( FOUR,      NUM,     Num,     RET )		/* '4' */\
	X( FIVE,      NUM,     Num,     RET )		/* '5' */\
	X( SIX,       NUM,     Num,     RET )		/* '6' */\
	X( SEVEN,     NUM,     Num,     RET )		/* '7' */\
	X( EIGHT,     NUM,     Num,     RET )		/* '8' */\
	X( NINE,      NUM,     Num,     RET )		/* '9' */\
	X( COLON,     NEXT,    Next,    JMP )		/* ':' */\
	X( SEMICOLON, NEXT,    Next,    JMP )		/* ';' */\
	X( LT,        LT,      Lt,      RET )		/* '<' */\
	X( EQ,        EQ,      Eq,      RET )		/* '=' */\
	X( GT,        GT,      Gt,      RET )		/* '>' */\
	X( QUESTION,  NEXT,    Next,    JMP )		/* '?' */\
	X( AT,        NEXT,    Next,    JMP )		/* '@' */\
	X( UPPER_A,   NEXT,    Next,    JMP )		/* 'A' */\
	X( UPPER_B,   NEXT,    Next,    JMP )		/* 'B' */\
	X( UPPER_C,   NEXT,    Next,    JMP )		/* 'C' */\
	X( UPPER_D,   NEXT,    Next,    JMP )		/* 'D' */\
	X( UPPER_E,   NEXT,    Next,    JMP )		/* 'E' */\
	X( UPPER_F,   NEXT,    Next,    JMP )		/* 'F' */\
	X( UPPER_G,   NEXT,    Next,    JMP )		/* 'G' */\
	X( UPPER_H,   NEXT,    Next,    JMP )		/* 'H' */\
	X( UPPER_I,   NEXT,    Next,    JMP )		/* 'I' */\
	X( UPPER_J,   NEXT,    Next,    JMP )		/* 'J' */\
	X( UPPER_K,   NEXT,    Next,    JMP )		/* 'K' */\
	X( UPPER_L,   NEXT,    Next,    JMP )		/* 'L' */\
	X( UPPER_M,   NEXT,    Next,    JMP )		/* 'M' */\
	X( UPPER_N,   NEXT,    Next,    JMP )		/* 'N' */\
	X( UPPER_O,   NEXT,    Next,    JMP )		/* 'O' */\
	X( UPPER_P,   NEXT,    Next,    JMP )		/* 'P' */\
	X( UPPER_Q,   NEXT,    Next,    JMP )		/* 'Q' */\
	X( UPPER_R,   NEXT,    Next,    JMP )		/* 'R' */\
	X( UPPER_S,   NEXT,    Next,    JMP )		/* 'S' */\
	X( UPPER_T,   NEXT,    Next,    JMP )		/* 'T' */\
	X( UPPER_U,   NEXT,    Next,    JMP )		/* 'U' */\
	X( UPPER_V,   NEXT,    Next,    JMP )		/* 'V' */\
	X( UPPER_W,   NEXT,    Next,    JMP )		/* 'W' */\
	X( UPPER_X,   NEXT,    Next,    JMP )		/* 'X' */\
	X( UPPER_Y,   NEXT,    Next,    JMP )		/* 'Y' */\
	X( UPPER_Z,   NEXT,    Next,    JMP )		/* 'Z' */\
	X( LSB,       NEXT,    Next,    JMP )		/* '[' */\
	X( BSLASH,    NEXT,    Next,    JMP )		/* '\\' */\
	X( RSB,       NEXT,    Next,    JMP )		/* '}' */\
	X( CARET,     BXOR,    Bxor,    RET )		/* '^' */\
	X( USCORE,    NEXT,    Next,    JMP )		/* '_' */\
	X( GRAVE,     NEXT,    Next,    JMP )		/* '`' */\
	X( LOWER_A,   NEXT,    Next,    JMP )		/* 'a' */\
	X( LOWER_B,   NEXT,    Next,    JMP )		/* 'b' */\
	X( LOWER_C,   NEXT,    Next,    JMP )		/* 'c' */\
	X( LOWER_D,   NEXT,    Next,    JMP )		/* 'd' */\
	X( LOWER_E,   NEXT,    Next,    JMP )		/* 'e' */\
	X( LOWER_F,   NEXT,    Next,    JMP )		/* 'f' */\
	X( LOWER_G,   NEXT,    Next,    JMP )		/* 'g' */\
	X( LOWER_H,   NEXT,    Next,    JMP )		/* 'h' */\
	X( LOWER_I,   NEXT,    Next,    JMP )		/* 'i' */\
	X( LOWER_J,   NEXT,    Next,    JMP )		/* 'j' */\
	X( LOWER_K,   NEXT,    Next,    JMP )		/* 'k' */\
	X( LOWER_L,   NEXT,    Next,    JMP )		/* 'l' */\
	X( LOWER_M,   NEXT,    Next,    JMP )		/* 'm' */\
	X( LOWER_N,   NEXT,    Next,    JMP )		/* 'n' */\
	X( LOWER_O,   NEXT,    Next,    JMP )		/* 'o' */\
	X( LOWER_P,   NEXT,    Next,    JMP )		/* 'p' */\
	X( LOWER_Q,   NEXT,    Next,    JMP )		/* 'q' */\
	X( LOWER_R,   NEXT,    Next,    JMP )		/* 'r' */\
	X( LOWER_S,   NEXT,    Next,    JMP )		/* 's' */\
	X( LOWER_T,   NEXT,    Next,    JMP )		/* 't' */\
	X( LOWER_U,   NEXT,    Next,    JMP )		/* 'u' */\
	X( LOWER_V,   NEXT,    Next,    JMP )		/* 'v' */\
	X( LOWER_W,   NEXT,    Next,    JMP )		/* 'w' */\
	X( LOWER_X,   NEXT,    Next,    JMP )		/* 'x' */\
	X( LOWER_Y,   NEXT,    Next,    JMP )		/* 'y' */\
	X( LOWER_Z,   NEXT,    Next,    JMP )		/* 'z' */\
	X( LCB,       NEXT,    Next,    JMP )		/* '{' */\
	X( VBAR,      BOR,     Bor,     RET )		/* '|' */\
	X( RCB,       NEXT,    Next,    JMP )		/* '}' */\
	X( TILDE,     BNOT,    Bnot,   RET )		/* '~' */\
	X( DEL,       NEXT,    Next,    JMP )		/* 127 */

#define X_ASCII_ENUM( ENUM, LABEL, FN, ACTION ) ASCII_##ENUM,
typedef enum Ascii { X_ASCIIS( X_ASCII_ENUM )  } Ascii;

#endif