#ifndef _ASCII_H
#define _ASCII_H
/* Mostly for reference. We cast in the lexer for compile safety. Comment the default to find what's missing. */
typedef enum Ascii {
	ASCII_NUL,			/* '\0' */
	ASCII_SOH,			/* 1 */
	ASCII_STX,			/* 2 */
	ASCII_ETX,			/* 3 */
	ASCII_EOT,			/* 4 */
	ASCII_ENQ,			/* 5 */
	ASCII_ACK,			/* 6 */
	ASCII_BEL,			/* 7 */
	ASCII_BS,			/* 8 */
	ASCII_HT,			/* 9 */
	ASCII_LF,			/* '\n' */
	ASCII_VT,			/* '\t' */
	ASCII_FF,			/* '\f' */
	ASCII_CR,			/* '\r' */
	ASCII_SO,			/* 14 */
	ASCII_SI,			/* 15 */
	ASCII_DLE,			/* 16 */
	ASCII_DC1,			/* 17 */
	ASCII_DC2,			/* 18 */
	ASCII_DC3,			/* 19 */
	ASCII_DC4,			/* 20 */
	ASCII_NAK,			/* 21 */
	ASCII_SYN,			/* 22 */
	ASCII_ETB,			/* 23 */
	ASCII_CAN,			/* 24 */
	ASCII_EM,			/* 25 */
	ASCII_SUB,			/* 26 */
	ASCII_ESC,			/* 27 */
	ASCII_FS,			/* 28 */
	ASCII_GS,			/* 29 */
	ASCII_RS,			/* 30 */
	ASCII_US,			/* 31 */
	ASCII_SPACE,		/* ' ' */
	ASCII_EXCL,			/* '!' */
	ASCII_DQUOTE,		/* '"' */
	ASCII_POUND,		/* '#' */
	ASCII_DOLLAR,		/* '$' */
	ASCII_PERCENT,		/* '%' */
	ASCII_AMPER,		/* '&' */
	ASCII_SQUOTE,		/* '\'' */
	ASCII_LP,			/* '(' */
	ASCII_RP,			/* ')' */
	ASCII_ASTERISK,		/* '*' */
	ASCII_PLUS,			/* '+' */
	ASCII_COMMA,		/* ',' */
	ASCII_HYPHEN,		/* '-' */
	ASCII_PERIOD,		/* '.' */
	ASCII_FSLASH,		/* '/' */
	ASCII_ZERO,			/* '0' */
	ASCII_ONE,			/* '1' */
	ASCII_TWO,			/* '2' */
	ASCII_THREE,		/* '3' */
	ASCII_FOUR,			/* '4' */
	ASCII_FIVE,			/* '5' */
	ASCII_SIX,			/* '6' */
	ASCII_SEVEN,		/* '7' */
	ASCII_EIGHT,		/* '8' */
	ASCII_NINE,			/* '9' */
	ASCII_COLON,		/* ':' */
	ASCII_SEMICOLON,	/* ';' */
	ASCII_LT,			/* '<' */
	ASCII_EQ,			/* '=' */
	ASCII_GT,			/* '>' */
	ASCII_QUESTION,		/* '?' */
	ASCII_AT,			/* '@' */
	ASCII_UPPER_A,		/* 'A' */
	ASCII_UPPER_B,		/* 'B' */
	ASCII_UPPER_C,		/* 'C' */
	ASCII_UPPER_D,		/* 'D' */
	ASCII_UPPER_E,		/* 'E' */
	ASCII_UPPER_F,		/* 'F' */
	ASCII_UPPER_G,		/* 'G' */
	ASCII_UPPER_H,		/* 'H' */
	ASCII_UPPER_I,		/* 'I' */
	ASCII_UPPER_J,		/* 'J' */
	ASCII_UPPER_K,		/* 'K' */
	ASCII_UPPER_L,		/* 'L' */
	ASCII_UPPER_M,		/* 'M' */
	ASCII_UPPER_N,		/* 'N' */
	ASCII_UPPER_O,		/* 'O' */
	ASCII_UPPER_P,		/* 'P' */
	ASCII_UPPER_Q,		/* 'Q' */
	ASCII_UPPER_R,		/* 'R' */
	ASCII_UPPER_S,		/* 'S' */
	ASCII_UPPER_T,		/* 'T' */
	ASCII_UPPER_U,		/* 'U' */
	ASCII_UPPER_V,		/* 'V' */
	ASCII_UPPER_W,		/* 'W' */
	ASCII_UPPER_X,		/* 'X' */
	ASCII_UPPER_Y,		/* 'Y' */
	ASCII_UPPER_Z,		/* 'Z' */
	ASCII_LSB,			/* '[' */
	ASCII_BSLASH,		/* '\\' */
	ASCII_RSB,			/* '}' */
	ASCII_CARET,		/* '^' */
	ASCII_USCORE,		/* '_' */
	ASCII_GRAVE,		/* '`' */
	ASCII_LOWER_A,		/* 'a' */
	ASCII_LOWER_B,		/* 'b' */
	ASCII_LOWER_C,		/* 'c' */
	ASCII_LOWER_D,		/* 'd' */
	ASCII_LOWER_E,		/* 'e' */
	ASCII_LOWER_F,		/* 'f' */
	ASCII_LOWER_G,		/* 'g' */
	ASCII_LOWER_H,		/* 'h' */
	ASCII_LOWER_I,		/* 'i' */
	ASCII_LOWER_J,		/* 'j' */
	ASCII_LOWER_K,		/* 'k' */
	ASCII_LOWER_L,		/* 'l' */
	ASCII_LOWER_M,		/* 'm' */
	ASCII_LOWER_N,		/* 'n' */
	ASCII_LOWER_O,		/* 'o' */
	ASCII_LOWER_P,		/* 'p' */
	ASCII_LOWER_Q,		/* 'q' */
	ASCII_LOWER_R,		/* 'r' */
	ASCII_LOWER_S,		/* 's' */
	ASCII_LOWER_T,		/* 't' */
	ASCII_LOWER_U,		/* 'u' */
	ASCII_LOWER_V,		/* 'v' */
	ASCII_LOWER_W,		/* 'w' */
	ASCII_LOWER_X,		/* 'x' */
	ASCII_LOWER_Y,		/* 'y' */
	ASCII_LOWER_Z,		/* 'z' */
	ASCII_LCB,			/* '{' */
	ASCII_VBAR,			/* '|' */
	ASCII_RCB,			/* '}' */
	ASCII_TILDE,		/* '~' */
	ASCII_DEL			/* 127 */
} Ascii;

#endif