#ifdef TYPES
#define JMP continue
#define RET return
#define X_ASCIIS( X )\
	/* ENUM       TK    LABEL    FN       ACTION */\
	X( NUL,       EOS, Eos,      RET )		/* '\0' */\
	X( SOH,       EOS, Next,     JMP )		/* 1 */\
	X( STX,       EOS, Next,     JMP )		/* 2 */\
	X( ETX,       EOS, Next,     JMP )		/* 3 */\
	X( EOT,       EOS, Next,     JMP )		/* 4 */\
	X( ENQ,       EOS, Next,     JMP )		/* 5 */\
	X( ACK,       EOS, Next,     JMP )		/* 6 */\
	X( BEL,       EOS, Next,     JMP )		/* 7 */\
	X( BS,        EOS, Next,     JMP )		/* 8 */\
	X( HT,        EOS, Next,     JMP )		/* 9 */\
	X( LF,        EOS, Line,     JMP )		/* '\n' */\
	X( VT,        EOS, Next,     JMP )		/* '\t' */\
	X( FF,        EOS, Next,     JMP )		/* '\f' */\
	X( CR,        EOS, Next,     JMP )		/* '\r' */\
	X( SO,        EOS, Next,     JMP )		/* 14 */\
	X( SI,        EOS, Next,     JMP )		/* 15 */\
	X( DLE,       EOS, Next,     JMP )		/* 16 */\
	X( DC1,       EOS, Next,     JMP )		/* 17 */\
	X( DC2,       EOS, Next,     JMP )		/* 18 */\
	X( DC3,       EOS, Next,     JMP )		/* 19 */\
	X( DC4,       EOS, Next,     JMP )		/* 20 */\
	X( NAK,       EOS, Next,     JMP )		/* 21 */\
	X( SYN,       EOS, Next,     JMP )		/* 22 */\
	X( ETB,       EOS, Next,     JMP )		/* 23 */\
	X( CAN,       EOS, Next,     JMP )		/* 24 */\
	X( EM,        EOS, Next,     JMP )		/* 25 */\
	X( SUB,       EOS, Next,     JMP )		/* 26 */\
	X( ESC,       EOS, Next,     JMP )		/* 27 */\
	X( FS,        EOS, Next,     JMP )		/* 28 */\
	X( GS,        EOS, Next,     JMP )		/* 29 */\
	X( RS,        EOS, Next,     JMP )		/* 30 */\
	X( US,        EOS, Next,     JMP )		/* 31 */\
	X( SPACE,     EOS, Next,     JMP )		/* ' ' */\
	X( EXCL,      EOS, Not,      RET )		/* '!' */\
	X( DQUOTE,    EOS, Str,      RET )		/* '"' */\
	X( POUND,     EOS, Next,     JMP )		/* '#' */\
	X( DOLLAR,    EOS, Comment,  JMP )		/* '$' */\
	X( PERCENT,   EOS, Mod,      RET )		/* '%' */\
	X( AMPER,     EOS, Band,     RET )		/* '&' */\
	X( SQUOTE,    EOS, Next,     JMP )		/* '\'' */\
	X( LP,        EOS, Lp,       RET )		/* '(' */\
	X( RP,        EOS, Rp,       RET )		/* ')' */\
	X( ASTERISK,  EOS, Mul,      RET )		/* '*' */\
	X( PLUS,      EOS, Add,      RET )		/* '+' */\
	X( COMMA,     EOS, Comma,    RET )		/* ',' */\
	X( HYPHEN,    EOS, Sub,      RET )		/* '-' */\
	X( PERIOD,    EOS, Period,   RET )		/* '.' */\
	X( FSLASH,    EOS, Div,      RET )		/* '/' */\
	X( ZERO,      NUM, Num,      RET )		/* '0' */\
	X( ONE,       NUM, Num,      RET )		/* '1' */\
	X( TWO,       NUM, Num,      RET )		/* '2' */\
	X( THREE,     NUM, Num,      RET )		/* '3' */\
	X( FOUR,      NUM, Num,      RET )		/* '4' */\
	X( FIVE,      NUM, Num,      RET )		/* '5' */\
	X( SIX,       NUM, Num,      RET )		/* '6' */\
	X( SEVEN,     NUM, Num,      RET )		/* '7' */\
	X( EIGHT,     NUM, Num,      RET )		/* '8' */\
	X( NINE,      NUM, Num,      RET )		/* '9' */\
	X( COLON,     EOS, Colon,    RET )		/* ':' */\
	X( SEMICOLON, EOS, Semi,     RET )		/* ';' */\
	X( LT,        EOS, Lt,       RET )		/* '<' */\
	X( EQ,        EOS, Eq,       RET )		/* '=' */\
	X( GT,        EOS, Gt,       RET )		/* '>' */\
	X( QUESTION,  EOS, Question, RET )		/* '?' */\
	X( AT,        EOS, At,       RET )		/* '@' */\
	X( UPPER_A,   ID,  Id,       RET )		/* 'A' */\
	X( UPPER_B,   ID,  Id,       RET )		/* 'B' */\
	X( UPPER_C,   ID,  Id,       RET )		/* 'C' */\
	X( UPPER_D,   ID,  Id,       RET )		/* 'D' */\
	X( UPPER_E,   ID,  Id,       RET )		/* 'E' */\
	X( UPPER_F,   ID,  Id,       RET )		/* 'F' */\
	X( UPPER_G,   ID,  Id,       RET )		/* 'G' */\
	X( UPPER_H,   ID,  Id,       RET )		/* 'H' */\
	X( UPPER_I,   ID,  Id,       RET )		/* 'I' */\
	X( UPPER_J,   ID,  Id,       RET )		/* 'J' */\
	X( UPPER_K,   ID,  Id,       RET )		/* 'K' */\
	X( UPPER_L,   ID,  Id,       RET )		/* 'L' */\
	X( UPPER_M,   ID,  Id,       RET )		/* 'M' */\
	X( UPPER_N,   ID,  Id,       RET )		/* 'N' */\
	X( UPPER_O,   ID,  Id,       RET )		/* 'O' */\
	X( UPPER_P,   ID,  Id,       RET )		/* 'P' */\
	X( UPPER_Q,   ID,  Id,       RET )		/* 'Q' */\
	X( UPPER_R,   ID,  Id,       RET )		/* 'R' */\
	X( UPPER_S,   ID,  Id,       RET )		/* 'S' */\
	X( UPPER_T,   ID,  Id,       RET )		/* 'T' */\
	X( UPPER_U,   ID,  Id,       RET )		/* 'U' */\
	X( UPPER_V,   ID,  Id,       RET )		/* 'V' */\
	X( UPPER_W,   ID,  Id,       RET )		/* 'W' */\
	X( UPPER_X,   ID,  Id,       RET )		/* 'X' */\
	X( UPPER_Y,   ID,  Id,       RET )		/* 'Y' */\
	X( UPPER_Z,   ID,  Id,       RET )		/* 'Z' */\
	X( LSB,       EOS, Next,     JMP )		/* '[' */\
	X( BSLASH,    EOS, Next,     JMP )		/* '\\' */\
	X( RSB,       EOS, Next,     JMP )		/* '}' */\
	X( CARET,     EOS, Bxor,     RET )		/* '^' */\
	X( USCORE,    ID,  Id,       RET )		/* '_' */\
	X( GRAVE,     EOS, Next,     JMP )		/* '`' */\
	X( LOWER_A,   ID,  Id,       RET )		/* 'a' */\
	X( LOWER_B,   ID,  Id,       RET )		/* 'b' */\
	X( LOWER_C,   ID,  Id,       RET )		/* 'c' */\
	X( LOWER_D,   ID,  Id,       RET )		/* 'd' */\
	X( LOWER_E,   ID,  Id,       RET )		/* 'e' */\
	X( LOWER_F,   ID,  Id,       RET )		/* 'f' */\
	X( LOWER_G,   ID,  Id,       RET )		/* 'g' */\
	X( LOWER_H,   ID,  Id,       RET )		/* 'h' */\
	X( LOWER_I,   ID,  Id,       RET )		/* 'i' */\
	X( LOWER_J,   ID,  Id,       RET )		/* 'j' */\
	X( LOWER_K,   ID,  Id,       RET )		/* 'k' */\
	X( LOWER_L,   ID,  Id,       RET )		/* 'l' */\
	X( LOWER_M,   ID,  Id,       RET )		/* 'm' */\
	X( LOWER_N,   ID,  Id,       RET )		/* 'n' */\
	X( LOWER_O,   ID,  Id,       RET )		/* 'o' */\
	X( LOWER_P,   ID,  Id,       RET )		/* 'p' */\
	X( LOWER_Q,   ID,  Id,       RET )		/* 'q' */\
	X( LOWER_R,   ID,  Id,       RET )		/* 'r' */\
	X( LOWER_S,   ID,  Id,       RET )		/* 's' */\
	X( LOWER_T,   ID,  Id,       RET )		/* 't' */\
	X( LOWER_U,   ID,  Id,       RET )		/* 'u' */\
	X( LOWER_V,   ID,  Id,       RET )		/* 'v' */\
	X( LOWER_W,   ID,  Id,       RET )		/* 'w' */\
	X( LOWER_X,   ID,  Id,       RET )		/* 'x' */\
	X( LOWER_Y,   ID,  Id,       RET )		/* 'y' */\
	X( LOWER_Z,   ID,  Id,       RET )		/* 'z' */\
	X( LCB,       EOS, Next,     JMP )		/* '{' */\
	X( PIPE,      EOS, Bor,      RET )		/* '|' */\
	X( RCB,       EOS, Next,     JMP )		/* '}' */\
	X( TILDE,     EOS, Bnot,     RET )		/* '~' */\
	X( DEL,       EOS, Next,     JMP )		/* 127 */
#define X_ASCII_ENUM( ENUM, TK, FN, ACTION ) ASCII_##ENUM,
typedef enum Ascii { X_ASCIIS( X_ASCII_ENUM )  } Ascii;
#endif